baseURL: "https://www.inteck3d.com/"
DefaultContentLanguage: en
relativeURLs: true

title: Inteck3d Inc.
description: See It, Build It! 3d Architectural Design & Rendering Specialists to help you visualize your renovation, dream home or condo project before it is built.

menu:
  main:
    - name: Home
      url: '/'
      weight: 1
    - name: About
      url: 'about/'
      weight: 2
    - name: Services
      url: 'services/'
      weight: 3
    - name: Portfolio
      url: 'portfolio/'
      weight: 4
    - name: Contact
      url: 'contact/'
      weight: 5


params:
    name: 'Inteck3D'
    showLanguageSelector: false #true if bilingual site - false if unilingua
    usebasin: 'https://usebasin.com/f/4f17a83c28f7' #endpoint for forms
    googlemap: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11199.734823199926!2d-74.1596675!3d45.4308377!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x9b82c8e93788adcd!2sInteck3d%20Inc.!5e0!3m2!1sen!2sca!4v1614785635738!5m2!1sen!2sca' # Map code of Google
    gtm: 'GTM-MJ4X83J'
    hours:
        hour1en: 'Mon - Sat 9:00-17:00' #Footer Hours Line #1
        hour2en: 'Sun CLOSED' #Footer Hours Line #2
        hour3en: '' #Footer Hours Line #3
    social:
        facebook: ''
        twitter: ''
        pinterest: ''
        instagram: ''
        linkedin: 'https://www.linkedin.com/company/inteck3d-inc.'

    schema:
        type: ProfessionalService
        priceRange: $$$
        reservation: 'false'
        openinghour: 'Mo-Sa 9:00-17:00'
        logo: "img/LogoTrans.png"
        logofooter: "img/footer.png"
        image: "img/og.jpg"
        address: 2658, rue Yearling
        address2: 
        city: Saint-Lazare
        region: QC
        country: Canada
        postalcode: J7T 2A1
        phone: +1-514-616-0158
        email: info@inteck3d.com

enableRobotsTXT: true
disableAliases: true
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: monthly
  filename: sitemap.xml

imaging:
  resampleFilter: box
  quality: 85
  anchor: smart