baseURL: "/"
DefaultContentLanguage: en
relativeURLs: true


title: ProfiClean
description: ProfiClean offers exceptional cleaning services and probiotic cleaning products. For residential and commercial services, and products for your home, call today!
contentDir: content/en
menu:
  main:
    - name: Home
      url: '/'
      weight: 1
    - name: About
      url: 'about/'
      weight: 2
    - name: Services
      url: 'services/'
      weight: 3
    - name: Products
      url: 'products/'
      weight: 4
    - name: Contact
      url: 'contact/'
      weight: 5


params:
    name: 'Inteck3D'
    showLanguageSelector: false #true if bilingual site - false if unilingua
    usebasin: 'https://usebasin.com/f/9d4f0521adea' #endpoint for forms
    googlemap: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2799.9633148368903!2d-73.82560598421715!3d45.43024084372952!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cc93fafae393647%3A0x23aec3743ffadd38!2sNetComp%20Technologies%20Inc!5e0!3m2!1sen!2sca!4v1609950957548!5m2!1sen!2sca' # Map code of Google
    gtm: 'GTM-PM8D6TS'
    hours:
        hour1en: 'Everyday - 5:00-23:00' #Footer Hours Line #1
        hour2en: '' #Footer Hours Line #2
        hour3en: '' #Footer Hours Line #3
    social:
        facebook: ''
        twitter: ''
        pinterest: ''
        instagram: ''
        linkedin: ''
    schema:
        type: ProfessionalService
        priceRange: $$$
        reservation: 'false'
        openinghour: 'Mo-Su 5:00-23:00'
        logo: "img/logo.jpg"
        logofooter: "img/logo.jpg"
        image: "img/og.jpg"
        address: 
        address2: 
        city: Saint-Jean-sur-Richelieu
        region: QC
        country: Canada
        postalcode: H9S 4R5
        phone: +1-514-337-4499
        email: proficleanmontreal@gmail.com

enableRobotsTXT: true
disableAliases: true
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: monthly
  filename: sitemap.xml

imaging:
  resampleFilter: box
  quality: 85
  anchor: smart