[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "https://infallible-heyrovsky-0bdc79.netlify.app/"
  to = "https://www.raincoastrentals.ca/"
  status = 301
  force = true #COMMENT: ensure that we always redirect