[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"

[[redirects]]
  from = "https://www.inteck3d.com/new-home"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSchF8NBXqDNC1ta0eS6j6MbEJY3RihFJpJ_i8gY33nvSrGROg/viewform"
  status = 301

[[redirects]]
  from = "https://www.inteck3d.com/meet-ivan"
  to = "https://www.inteck3d.com/meeting"
  status = 301


[[redirects]]
  from = "https://inteck3d.netlify.app/"
  to = "https://www.inteck3d.com/"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404




  
