[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404


[[redirects]]
  from = "https://Inteck3d.com"
  to = "https://www.Inteck3d.com"
  status = 301
  force = true #COMMENT: ensure that we always redirect

  

[[redirects]]
  from = "https://Inteck3d.pages.dev"
  to = "https://www.Inteck3d.com"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://*.Inteck3d.pages.dev"
  to = "https://www.Inteck3d.com"
  status = 301
  force = true #COMMENT: ensure that we always redirect