[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "https://inteck3d.netlify.app/"
  to = "https://www.inteck3d.com/"
  status = 301
  force = true #COMMENT: ensure that we always redirect